name: Generate Solas Report

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: 'Dataset name (e.g., iris, wine, titanic)'
        required: true

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run EDA Report
        run: python eda_report.py ${{ github.event.inputs.dataset }}

      - name: Commit report
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/
          git commit -m "Auto-generate report for ${{ github.event.inputs.dataset }}"
          git push
