name: Fetch Solas EDA Report

on:
  workflow_dispatch:

jobs:
  fetch-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI and Download Report
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<< "${DATABRICKS_HOST}\n${DATABRICKS_TOKEN}"
          databricks fs cp dbfs:/FileStore/solas_report.html ./docs/solas_report.html --overwrite

      - name: Push Report to GitHub Pages
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/solas_report.html
          git commit -m "Update Solas EDA Report"
          git push
